name: guffy
description: "A modern social media app built with Flutter."
publish_to: 'none' # প্রাইভেট প্রোজেক্টের জন্য

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Icons & UI
  cupertino_icons: ^1.0.8

  # Firebase Packages (Backend & Storage)
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4

  # State Management
  provider: ^6.1.2

  # Image & Media Handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # Monetization (Google AdMob)
  google_mobile_ads: ^5.2.0

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # আপনার কোনো ইমেজ বা ফন্ট অ্যাসেট থাকলে এখানে আনকমেন্ট করে পাথ দেবেন:
  # assets:
  #   - assets/images/
